# Generated by Django 3.2 on 2024-11-20 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('tipo_producto', models.CharField(max_length=20)),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('precio_producto', models.FloatField()),
                ('stock_producto', models.IntegerField()),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='CarroDeCompras',
            fields=[
                ('id_carro', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='AppMagilou.usuario')),
            ],
            options={
                'db_table': 'Carro_de_compras',
            },
        ),
        migrations.CreateModel(
            name='CarroProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('id_carro', models.ForeignKey(db_column='id_carro', on_delete=django.db.models.deletion.CASCADE, to='AppMagilou.carrodecompras')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='AppMagilou.producto')),
            ],
            options={
                'db_table': 'Carro_Producto',
                'unique_together': {('id_carro', 'id_producto')},
            },
        ),
    ]
