# Generated by Django 3.2 on 2024-11-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagilou', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrodecompras',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='carroproducto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
