# Generated by Django 3.2 on 2024-11-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagilou', '0002_auto_20241121_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
