# Generated by Django 3.2 on 2024-11-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMagilou', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
